.TH "KURLOAD" "1" "30 Nov 2017 (v1.0.0)" "bofc.pl"

.SH NAME
\fBkurload\fR - share files or program output from command line using the most
basic UNIX tools

.SH SYNOPSIS
\fBkurload\fR [ \fB-h\fR | \fB-v\fR | \fB-d\fR \fB-c\fR \fB-l\fR <\fIlevel\fR>
\fB-f\fR <\fIconfig\fR> ]

.SH OPTIONS

.TP
\fB-h\fR
Prints short help and exits

.TP
\fB-v\fR
Prints version number and exits

.TP
\fB-d\fR
Run program as daemon.

.TP
\fB-c\fR
When enabled, colors will be added to program logs. Usefull for spotting
errors and warnings, but might not work with all terminals and tools.

.TP
\fB-l\fR \fIlevel\fR
Verbosity of logs can be on of

.RS 12
0   fatal errors, application cannot continue
.br
1   major failure, needs immediate attention
.br
2   critical errors
.br
3   error but recoverable
.br
4   warnings
.br
5   normal message, but of high importance
.br
6   info log, doesn't print that much (default)
.br
7   debug, not needed in production
.RE

.TP
\fB-f\fR \fIconfig\fR
Path to configuration file. Default "/etc/kurload/kurload.conf"

.SH DESCRIPTION
Server allows uploading any binary file using only the most basic UNIX tools
like \fBnetcat\fR. Because netcat doesn't send file size information, one should
append "kurload\\n" string at the end of upload to indicate end of file. File
can be uploaded like this

.RS 4
cat /path/to/file | cat - <(echo 'kurload') | nc kurwinet.pl 1337'
.RE

Quite long and irritating. It is recommended to create alias to work-around this
tedious work.

.RS 4
alias kl="cat - <(echo 'kurload') | nc kurwinet.pl 1337"
.RE

Now you can upload file as simple as calling

.RS 4
cat /path/to/file | kl
.RE

Note that process substitution \fB<()\fR only works with bash-compatible shell.


.SH FILES
These are default file locations. They can be changed in configuration file

.TP
\fB/etc/kurload/kurload.conf\fR
Configuration file for \fBkurload\fR

.TP
\fB/etc/kurload/whitelist\fR
Separated by new line list of IPs that are allowed to upload - only when program
operates in whitelist mode

.TP
\fB/etc/kurload/blacklist\fR
Separated by new line list of IPs that are blocked from uploading - only used
when program operates in blacklist mode

.TP
\fB/var/run/kurload.pid\fR
Process id of working daemon. This file is created only when program is run with
\fB-d\fR option

.TP
\fB/var/log/kurload-query.log\fR
Every upload query will be logged here exactly once. If query failed, short
reason is added and more information about failure can be found in program. For
successful queries, filename is loged. All queries will contain date of upload
and source IP.

.TP
\fB/var/log/kurload.log\fR
Program log is kept here. Detailed information about errornous queries will be
here.

.TP
\fB/var/lib/kurload\fR
Directory where all uploaded files are stored - usually root of http from
where people can download files.

.SH "CONFIGURATION FILE"
Please refer to comments in \fB/etc/kurload/kurload.conf\fR to learn how to
configure program.

.SH "BUG REPORTING"
Please report all bugs to "Michał Łyszczek <michal.lyszczek@bofc.pl>"
