#!/bin/bash

kurload()
{
    cat - <(echo 'kurload') | nc 127.6.13.37 61337 2>/dev/null
}

mkdir -p /tmp/kurload-test/out
i=0


../src/kurload -D -l6 -c -i61337 -s1024 -t1 -m2 -dlocalhost -ukurload \
    -gkurload -P/tmp/kurload-test/kurload.pid \
    -q/tmp/kurload-test/kurload-query.log -p/tmp/kurload-test/kurload.log \
    -L/tmp/kurload-test/blacklist -T-1 -o/tmp/kurload-test/out \
    -b127.6.13.37
data=`head -c 1000 < /dev/urandom`

while :
do
    ((i++))
    echo "$data" | kurload >/dev/null 2>&1  &
    if [ $i -eq 10000 ]
    then
        i=0
        rm /tmp/kurload-test/out/*
        echo "" > /tmp/kurload-test/kurload-query.log
    fi
done

kill -15 `cat /tmp/kurload-test/kurload.pid`
rm -rf /tmp/kurload-test
