#!/bin/sh

set -e

if ! getent group kurload >/dev/null; then
    groupadd --system kurload
fi

if ! getent passwd kurload >/dev/null; then
    adduser --system --home /var/lib/kurload --shell /usr/sbin/nologin \
        --gid $(getent group kurload | cut -f3 -d:) kurload
fi

chown kurload:kurload /var/lib/kurload

#DEBHELPER#
